### ISSUE TITLE
Required wlroots is not clear.

### ISSUE THREAD

**Issue by lidgnulinux** [vilfa/bonsai#3]
I have 2 wlroots version, 0.15.X from debian package and 0.16.X locally installed. The compilations are error for both those version of wlroots. Which version of wlroots needed ? Thanks.

**Comment by vilfa** [comment]
For building, I used the June 14th commit from wlroots main repo. Should be commit [f28c0e2046c59aeb9f014ef4c22d4517e38f4721](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/f28c0e2046c59aeb9f014ef4c22d4517e38f4721). Although, I think you should be able to use wlroots-latest.

**Comment by lidgnulinux** [comment]
I use wlroots-master and still fail to build. Maybe I need to use the same wlroots like yours.
[ninja-build.txt](https://github.com/vilfa/bonsai/files/9149498/bonsai-ninja.txt)

**Comment by vilfa** [comment]
Hmm, it seems they've removed the anon union that allows direct access to the underlying device (see this commit [https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/91943a68a6976ef7c4cc70afc07954a00fae678b#d10977f8d9e31c12b95f72ee595be4af3ddb7f92](diff)). Looks like you should be using the newly provided `[https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/91943a68a6976ef7c4cc70afc07954a00fae678b#ac2467f4be2d30466edf75e51f40edfc87ed4ea7](wlr_keyboard_from_input_device())` function.

So you've got multiple options:
1. use the new function where necessary (replace e.g. `&device->device->keyboard->events.key` with something like `wlr_keyboard_from_input_device(&device->device)->events.key`), or
2. use the June 14th commit I mentioned in the first comment

Note: there are new functions for getting the underlying device for all possible device types (`wlr_keyboard_from_input_device()`, `wlr_pointer_from_input_device()`,...), so use them if you run into any similar errors. You can also manually cast into the proper type (there is a `void* data` member in `struct wlr_input_device`, and an `enum wlr_input_device_type type`, that tags its type)

**Comment by vilfa** [comment]
Closing this. If you have other questions, open another issue.
