### ISSUE TITLE
Add simple README and list of shortcuts, tap to click not active.

### ISSUE THREAD

**Issue by lidgnulinux** [vilfa/bonsai#6]
I'm glad I can make it to build and install. It will be nice to include a Readme file and give a list of shortcuts, It's just and advice tho. BTW It's nice compositor and I'll give it some days for daily driver.
Additional issue : turns out tap to click still not active.

**Comment by lidgnulinux** [comment]
Found some shortcuts [here](https://github.com/vilfa/bonsai/blob/a5582545ed86d8cf3d524107163a995b40e4ca30/bonsai/input/keyboard.c)

**Comment by vilfa** [comment]
Right, will add README. Note: The compositor probably isn't really ready to be a daily driver from a stability standpoint, also somewhat buggy, although I'm happy for you to give it a go and report any stuff you find that isn't as expected. Thanks :)

**Comment by vilfa** [comment]
About the tap to click issue:
1. You should be running the compositor directly, not as a client of KWin or another compositor.
2. The right device name should be set for your device (laptop touchpad). This will usually be something like `SYNA30BD:00 06CB:CE08` -- you will find this in the logs, where it prints out all devices.

So the pointer part of your config might look something like this:
```
input pointer "SYNA30BD:00 06CB:CE08" accel_speed 0.0
input pointer "SYNA30BD:00 06CB:CE08" accel_profile flat
input pointer "SYNA30BD:00 06CB:CE08" scroll_natural yes
input pointer "SYNA30BD:00 06CB:CE08" tap yes
```

**Comment by lidgnulinux** [comment]
> The compositor probably isn't really ready to be a daily driver from a stability standpoint...

Nevermind, I'm happy to discover and try something new.

**Comment by lidgnulinux** [comment]
I thought the easiest way to find touchpad device perhaps using `libinput` command, I just tried it and it works, tap to click is active now. Thanks.

```
$ sudo libinput list-devices | grep -i touchpad
```

**Comment by vilfa** [comment]
Added README, including keyboard shortcuts.
